"""
models.py
=========
SQLAlchemy ORM models for the PlaceBuddy MCQ engine.

Schema Design Rationale
-----------------------
Table: mcq_questions
--------------------
Each row represents one fully self-contained MCQ question tied to a specific
technical skill.  Questions are cached permanently — once generated by Gemini,
they are never regenerated for the same (skill, forensic_tier, difficulty)
combination.

Column Details
~~~~~~~~~~~~~~
id              SERIAL PRIMARY KEY
                Auto-incrementing integer. Chosen over UUID for simpler
                ORDER BY and JOIN operations in the quiz assembly logic.

skill           VARCHAR(120) NOT NULL
                Normalized lowercase skill name (e.g. "react", "kubernetes").
                Indexed for fast skill-based lookups.

forensic_tier   VARCHAR(10) NOT NULL
                One of: 'Green' | 'Yellow' | 'Red'.
                Maps to confidence tiers in the ATS output:
                    Green  -> verified competency (proficiency >= 70)
                    Yellow -> unverified / stated-only skill (30-70)
                    Red    -> missing/critical gap (< 30 or absent)
                This enables the quiz assembly to respect the target
                distribution:  2 Green + 4 Yellow + 4 Red = 10 questions.

difficulty      VARCHAR(20) NOT NULL  default='medium'
                One of: 'easy' | 'medium' | 'hard'.
                Allocated per-question by the seniority resolver:
                    junior -> 4 Easy + 5 Medium + 1 Hard
                    mid    -> 2 Easy + 5 Medium + 3 Hard
                    senior -> 1 Easy + 4 Medium + 5 Hard
                Indexed as part of the composite for O(1) granular lookups.

seniority_tier  VARCHAR(20) nullable
                One of: 'junior' | 'mid' | 'senior'. Stored for analytics
                and future difficulty-drift tracking. NULL = unclassified.

question_text   TEXT NOT NULL
                The full question string.

options         JSON NOT NULL
                Array of exactly 4 answer strings.
                Stored as JSON to avoid a separate join table.

correct_answer  VARCHAR(512) NOT NULL
                Must match one of the values in `options` exactly.

explanation     TEXT NOT NULL
                The forensic explanation shown after quiz completion.
                Persisted so we never call Gemini twice for the same question.

Indexes
~~~~~~~
ix_mcq_skill            -- speeds up "fetch all questions for skill X"
ix_mcq_skill_diff_tier  -- composite (skill, difficulty, forensic_tier);
                           the primary access pattern for granular cache lookup
"""

from sqlalchemy import Column, Integer, String, Text, JSON, Index
from app.db.database import Base


class Question(Base):
    """MCQ question cache -- one row per question."""

    __tablename__ = "mcq_questions"

    id: int = Column(Integer, primary_key=True, index=True, autoincrement=True)

    # -- Skill metadata --------------------------------------------------------
    skill: str          = Column(String(120), nullable=False)
    forensic_tier: str  = Column(String(10),  nullable=False)  # Green | Yellow | Red

    # -- Difficulty / seniority metadata ---------------------------------------
    difficulty: str      = Column(String(20), nullable=False, default="medium")  # easy|medium|hard
    seniority_tier: str  = Column(String(20), nullable=True)                     # junior|mid|senior

    # -- Question content ------------------------------------------------------
    question_text: str  = Column(Text,        nullable=False)
    options: list       = Column(JSON,        nullable=False)   # List[str] -- 4 items
    correct_answer: str = Column(String(512), nullable=False)
    explanation: str    = Column(Text,        nullable=False)

    # -- Indexes ---------------------------------------------------------------
    # ix_mcq_skill            -- single-column fast lookup by skill name
    # ix_mcq_skill_diff_tier  -- three-column composite for the granular
    #                            (skill, difficulty, forensic_tier) access pattern
    __table_args__ = (
        Index("ix_mcq_skill",           "skill"),
        Index("ix_mcq_skill_diff_tier", "skill", "difficulty", "forensic_tier"),
    )

    def __repr__(self) -> str:
        return (
            f"<Question id={self.id} skill={self.skill!r} "
            f"tier={self.forensic_tier!r} diff={self.difficulty!r} "
            f"q={self.question_text[:40]!r}>"
        )
